SELECT * FROM TOPPINGS;
SELECT * FROM BASE_PRICE;
SELECT * FROM CUSTOMER;
SELECT * FROM PIZZA;
SELECT * FROM CUST_ORDER;
SELECT * FROM CHOICE_OF;
SELECT * FROM PIZZA_DISCOUNT;
SELECT * FROM ORDER_DISCOUNT;
SELECT * FROM DISCOUNT;
SELECT * FROM PERCENT_DISCOUNT;
SELECT * FROM DOLLAR_DISCOUNT;
SELECT * FROM DINE_IN;
SELECT * FROM SEAT_NUMBER;
SELECT * FROM PICKUP;
SELECT * FROM PICKUP_CUSTOMER;
SELECT * FROM DELIVERY;
SELECT * FROM DELIVERY_CUSTOMER;


